In [7]:
# Numpy basics with python
### Numpy is the most basic and powerful package in the python. Every data scientist must know about numpy, as many other packages are built over it. Like pandas, scikit-learn etc.

### At the core, numpy provides the excellent ndarray objects, short for n-dimensional arrays. 'ndarray' object also known as 'numpy array' can store multiple items of same data type. Hence, helping in lot of mathematical operations and data calculations.


#### `Create Numpy Array`
#### `A numpy array is a grid of values, with same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the *rank* of the array; the *shape* of an array is a tuple of integers giving the size of the array along each dimension. Array can handle vectorised operations while python list cannot, thus doing operations much faster`

In [29]:
import numpy as np
list1 = [1,2,3,4]
arr = np.array(list1)

print(type(arr))
print(arr)
print(arr.shape)

<class 'numpy.ndarray'>
[1 2 3 4]
(4,)


#### `Pass list of lists to create matrix like a 2d array`

In [30]:
list2 = [[1,2,3], [3,4,5], [4,5,6]]
arr2 = np.array(list2)

print(type(arr2))
print(arr2)
print(arr2.shape)

<class 'numpy.ndarray'>
[[1 2 3]
 [3 4 5]
 [4 5 6]]
(3, 3)


#### `we can also specify the datatype of the list, for example: 'float64'`

In [31]:
arr2_f = np.array(list2, dtype='float')
print(arr2_f)
arr3_f = np.array(list2, dtype="bool")
print(arr3_f)

[[1. 2. 3.]
 [3. 4. 5.]
 [4. 5. 6.]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


***
#### `Some ways to create a numpy array and fill with some values`

In [32]:
zero = np.zeros((2,2))      # Fills the array with zeros
print(zero) 
one = np.ones((1,2))        # Fills the array with ones
print(one)
full = np.full((2,2), 7)    # Fills the array with given value
print(full)
eye = np.eye(2)             # Fills the diagonal with one, nxn matrix
print(eye)
rand = np.random.random((2,2))  # Fills the array with random values
print(rand)

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.05940144 0.86111328]
 [0.07417381 0.15893197]]


***
#### `Indexing`
#### `Method - 1 : Slicing`

In [35]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
# [[ 1 2 3 4]
# [5 6 7 8]
# [9 10 11 12]]

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
b = a[:2, 1:3]
print(b)
# We can also modify the data using assignment operator
a[2, 0] = 102

[[2 3]
 [6 7]]
102


#### `Integer Indexing`

In [37]:
print(a[2, 0])

102


#### `Mixing slicing and integer indexing`

In [40]:
row1 = a[1, :]
print(row1)
col1 = a[:, 1]
print(col1)

[5 6 7 8]
[ 2  6 10]


#### `Boolean array indexing`

In [45]:
b = a > 4
print(b)
print(a[b])
print(a[a > 4])

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]
[  5   6   7   8 102  10  11  12]
[  5   6   7   8 102  10  11  12]
